// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfqxeorgdtgrrfxmadsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmcXhlb3JnZHRncnJmeG1hZHN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NzAxMzEsImV4cCI6MjA1OTA0NjEzMX0.My4K-XI47QouiYFVt1xbk19fbZ_nTSlPxiBFae240TQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);